### ISSUE TITLE
Notifications should be true by default

### ISSUE THREAD

**Issue by elanhickler** [djmcgill/dominions-5-status#74]
Why was the decision made to make notifications false by default? I want this to be a simple as possible for non-techies to use. Having to explain "hey you need to put in these two commands separately, don't copy and paste both at once" is annoying.

The help text needs to specify if it's true or false by default.

Another solution would be to provide a single line command to register and set notifications true in one line.

**Comment by djmcgill** [comment]
I entirely agree. That's why notifications are true by default. You're right that the help text should say it.

If you're having an issue where notifications are not being sent from just a !register command I am extremely interested in a reproducible case because something seriously weird is happening.

**Comment by djmcgill** [comment]
I should also say that I do value these issues you're raising. The documentation is NOT clear at all and it's increasingly obvious that I've been relying far too heavily on people being in our discord when working it out.

**Comment by elanhickler** [comment]
I'll let you know if I'm not getting notifications, most likely user error.
